### ISSUE TITLE
Have you got any examples of using values from the user table

### ISSUE THREAD

**Issue by Bengreen** [dpgaspar/Flask-AppBuilder#182]
I would like to use values from the user table to be able to assign users against items in tables. Have you got any examples of how to do this.

I was not able to work out where or how to access a user model. I am trying with using the generic model, but not sure if this is the right approach as it seems a bit counterintuitive.

**Comment by dpgaspar** [comment]
You can use AuditMixin to update your records with current timestamp and user:

``` python
from flask_appbuilder.models.mixins import AuditMixin
from flask_appbuilder import Model
from sqlalchemy import Column, Integer, String


class Project(AuditMixin, Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(150), unique=True, nullable=False)
 ```

Take a look at: http://flask-appbuilder.readthedocs.org/en/latest/security.html#auditing

To query the user table just import the User Model and use SQLAlchemy query:

``` python 
from flask_appbuilder.security.sqla.models import User

class YourModelView(ModelView):
    def query_all_users():
        return self.appbuilder.get_session.query(User).all()
```

Hope this helps.

**Comment by Bengreen** [comment]
Does that view not need a datamodel

**Comment by Bengreen** [comment]
What I was trying to do was like this.

class Transactionactor(Model):
    id = Column(Integer, primary_key=True)
    description = Column(String(100))
    supply_id = Column(Integer, ForeignKey('supply.id'),nullable=False)
    supply = relationship("Supply")
    transactiontype_id = Column(Integer, ForeignKey('transactiontype.id'),nullable=False)
    transactiontype = relationship("Transactiontype")
    user_id = Column(Integer, ForeignKey('ab_user.id'),nullable=False)   ### USING THIS LINE LOCKS UP SERVER

**Comment by dpgaspar** [comment]
Yes, the ModelView needs the datamodel, i've corrected the example.

```python
from flask_appbuilder.security.sqla.models import User

class Transactionactor(Model):
    id = Column(Integer, primary_key=True)
    description = Column(String(100))
    supply_id = Column(Integer, ForeignKey('supply.id'),nullable=False)
    supply = relationship("Supply")
    transactiontype_id = Column(Integer, ForeignKey('transactiontype.id'),nullable=False)
    transactiontype = relationship("Transactiontype")
    user_id = Column(Integer, ForeignKey('ab_user.id'),nullable=False)   ### USING THIS LINE LOCKS UP SERVER
    user = relationship("User")
```

Please try it with the relationship. What kind of backend are you using? Postgresql ?

**Comment by Bengreen** [comment]
I am using postgres.

I get still get the server locking (with no error messages, just a server lock).
Last entry on the log is : INFO:flask_appbuilder.base:Registering class PermissionViewModelView on menu Permission on Views/Menus

I think it is happening somewhere where the DB tables are being created. (I noticed that if the table already exists from a previous construct of the Transactionactor model then I dont get the server crash. When i go in and delete the transactionactor table and restart the server then i get the stall.

i have not deleted the ab_user table. Have kept away from this as i didn't think this was something i should be doing.

My View is simple:
```python
class TransactionactorView(ModelView):
    datamodel = SQLAInterface(Transactionactor)

    list_columns = ['description', 'user', 'supply', 'transactiontype']
```

**Comment by dpgaspar** [comment]
The lock problem with PG is related to this #81

**Comment by Bengreen** [comment]
Wow.. I would not have got that. Once I added that it now works a treat. Thank you. Keep up the great work.
